# Perfil para execução no Docker Compose
spring:
  application:
    name: auth-service
  
  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    com.distrischool: INFO
    org.springframework.kafka: WARN

