# Perfil para execução no Kubernetes
spring:
  application:
    name: auth-service
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    com.distrischool: INFO
    org.springframework.kafka: WARN
    org.springframework.cloud: INFO

# Configurações específicas para Kubernetes
management:
  endpoint:
    health:
      probes:
        enabled: true

