global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - microservice-auth-dev:8080


